version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend
    ports: ["5000:5000"]
    environment:
      - DB_HOST=main-db.citoyhzc0azx.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=Hola12345
      - DB_NAME=main-db
      - JWT_SECRET=miClaveSecreta123!